project:
  type: website
  output-dir: docs
  preview:
    port: 5555
    browser: false
    timeout: 3600
  render:
    - "index.qmd"
    - "slides/*.qmd"

website:
  title: ""
  navbar:
    logo: "NORSAR-main-logo-RGB.png"
    logo-href: "/"
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    #title-slide-attributes: 
    #  data-background-image: NORSAR-main-logo-RGB.png
    #  data-background-size: 15%
    #  data-background-position: 98% 2%
    code-line-numbers: false
highlight-style: atom-one
revealjs-plugins:
  - pointer
  
